### PR TITLE
Fixed barometric sensor readings

### PR DESCRIPTION
**Pull request by martin-doyle**
chart
Used current latest version of TI's Android source code to write this patch

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@martin-doyle thanks, nice work!

**Comment by sandeepmistry** [comment]
Note this change did not work with firmware version ```0.89 (Jan 31 2015)```, I had to update to ```1.01 (Mar 13 2015)``` via the iOS app.

**Comment by martin-doyle** [comment]
Yes, I use firmware 1.01 and did not check version 0.89.
Now, it is clear why TI tests for the data length: 
4 => old firmware 
>4 => new firmware

**Comment by sandeepmistry** [comment]
@martin-doyle hmm, I'm wondering if something similar should be done in node-sensortag ... thoughts?

**Pull request merged**
